bids_root: C:/Users/ncohe/Desktop/bci_vis/BIDS_dataset/motor_imagery_ds003810
task: MIvsRest
subjects: ["02", "04"]
runs: ["1","2"]

class_map:
  dominant_hand: 1
  rest: 2

event_id:
  OVTK_GDF_Right: 7 # MI
  OVTK_GDF_Tongue: 9 # rest

preprocessing:
  load_data: true
  already_filtered: true
  original_band: [0.5, 45]
  bandpass: [1, 40]
  notch_filter: 50
  tmin: 0.5
  tmax: 2.5
  baseline: [0.5, 1.0]  

visualization:
  duration: 100.0
  start: 20.0
  n_channels: 4
  scalings:
    eeg: 100.0
  use_montage: true
  montage_kind: standard_1020
  psd_fmin: 0.1
  psd_fmax: 60.0
  psd_average: False
  picks: eeg
  show_events: False
  topomap_times: [0.5, 1.0, 1.5]
  baseline: [0.5, 1.0]


sanity_check:
  enable_plots: true
  
output:
  base_directory: "C:/Users/ncohe/Desktop/bci_vis/results"

save_figures:
  enabled: true
  format: "png" 
  dpi: 300

