bids_root: D:/Niv/bci_vis/BIDS
task: MIvsRest
subjects: ["02", "04"]
runs: ["1","2"]

class_map:
  dominant_hand: 1
  rest: 2

event_id:
  OVTK_GDF_Right: 7 # MI
  OVTK_GDF_Tongue: 9 # rest

preprocessing:
  load_data: true
  already_filtered: true
  original_band: [0.5, 45]
  bandpass: [1, 40]
  notch_filter: 50
  tmin: 0.5
  tmax: 2.5
  baseline: [0.5, 1.0]  # or baseline: [None, 1.0] if you want "from beginning to 1.0s"

visualization:
  duration: 100.0
  start: 20.0
  n_channels: 4
  scalings:
    eeg: 100.0
  use_montage: true
  montage_kind: standard_1020
  psd_fmin: 0.1
  psd_fmax: 45.0
  psd_average: true
  picks: eeg

